services:
  # Node 1 (Main)
  db1:
    image: mysql:8.0
    container_name: blockchain_node_1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_db
    ports:
      - "3306:3306"
    volumes:
      - db1_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # Node 2 (Distributed)
  db2:
    image: mysql:8.0
    container_name: blockchain_node_2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_db
    ports:
      - "3307:3306"
    volumes:
      - db2_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # Node 3 (Distributed)
  db3:
    image: mysql:8.0
    container_name: blockchain_node_3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_db
    ports:
      - "3308:3306"
    volumes:
      - db3_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db1_data:
  db2_data:
  db3_data: